In [1]:
import tensorflow as tf

tfs = tf.InteractiveSession()

helloVar = tf.constant("Bismillah")

print(tfs.run(helloVar))

b'Bismillah'


In [2]:
c1 = tf.constant(5, name = "x")
print("c1 (x):", c1)

c1 (x): Tensor("x:0", shape=(), dtype=int32)


In [3]:
c2 = tf.constant(6.0, name = "y")
print("c2 (y):", c2)

c2 (y): Tensor("y:0", shape=(), dtype=float32)


In [4]:
c3 = tf.constant(7.0,dtype=tf.float32,name="z")
print("c3 (z):", c3)

c3 (z): Tensor("z:0", shape=(), dtype=float32)


In [ ]:
print("run(c1, c2, c3):", tfs.run([c1, c2, c3]))

run(c1, c2, c3): [5, 6.0, 7.0]


In [ ]:
op1 = tf.add(c3, c2)
print("op1: ", op1)
print("run(op1): ", tfs.run(op1))

op1:  Tensor("Add:0", shape=(), dtype=float32)
run(op1):  13.0


In [ ]:
op2 = tf.multiply(c3, c2)
print("op2: ", op2)
print("run(op2): ", tfs.run(op2))

op2:  Tensor("Mul:0", shape=(), dtype=float32)
run(op2):  42.0


In [ ]:
p1 = tf.placeholder(tf.float32, name="Px")
p2 = tf.placeholder(tf.float32, name="Py")
op3 = p1 * p2

print("P1 : ", p1)
print("P2 : ", p2)
print("run(op3): ", tfs.run(op3, feed_dict = {p1: 3.0, p2: 9.5}))
print("run(op3): ", tfs.run(op3, feed_dict = {p1: [3.0, 8.0], p2: [9.5, 1.0]}))

P1 :  Tensor("Px:0", dtype=float32)
P2 :  Tensor("Py:0", dtype=float32)
run(op3):  28.5
run(op3):  [28.5  8. ]


In [ ]:
import numpy as np

d2Array = np.array([(1, 2, 3),
                    (4, 5, 6),
                    (7, 8, 9)])
print('d2Array shape:', d2Array.shape)
tf_d2T = tf.convert_to_tensor(d2Array, dtype=tf.float64)

print('tf_d2T:', tf_d2T)
print('tf_d2T[0][0]:', tf_d2T[0][0])
print('run(tf_d2T): \n', tfs.run(tf_d2T))
print('run(tf_d2T[0][0]):', tfs.run(tf_d2T[0][0]))


d2Array shape: (3, 3)
tf_d2T: Tensor("Const_1:0", shape=(3, 3), dtype=float64)
tf_d2T[0][0]: Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_d2T): 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
run(tf_d2T[0][0]): 1.0


In [ ]:
w = tf.Variable([1.0, 1.0], tf.float32)
b = tf.Variable([1.0, 0.0], tf.float32)
x = tf.placeholder(tf.float32)
y = w * x - b

print('w: ', w)
print('b: ', b)
print('x: ', x)
print('y: ', y) 

tfs.run(tf.global_variables_initializer())

print('run(y, {x: [(1, 2), (3, 4)]}):',  tfs.run(y, {x: [(1, 2), (3, 4)]}))

w:  <tf.Variable 'Variable:0' shape=(2,) dtype=float32_ref>
b:  <tf.Variable 'Variable_1:0' shape=(2,) dtype=float32_ref>
x:  Tensor("Placeholder:0", dtype=float32)
y:  Tensor("sub:0", dtype=float32)
run(y, {x: [(1, 2), (3, 4)]}): [[0. 2.]
 [2. 4.]]


In [ ]:
tfs.close()

In [ ]:
w1 = tf.Variable([1.0], tf.float32)
b1 = tf.Variable([1.0], tf.float32)
x1 = tf.placeholder(tf.float32)
y1 = w1 * x1 - b1
output = 0

with tf.Session() as tfs:
    #init = tf.initialize_all_variables()
    init = tf.global_variables_initializer()
    tfs.run(init)
    
    print('output: ', tfs.run(y1, {x1: [1, 2, 3, 4]}))

output:  [0. 1. 2. 3.]


In [ ]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 634208950483809942
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 15705098699664175047
physical_device_desc: "device: XLA_CPU device"
]


In [ ]:
w2 = tf.Variable([1.0], tf.float32)
b2 = tf.Variable([1.0], tf.float32)
x2 = tf.placeholder(tf.float32)
y2 = w2 * x2 - b2
output = 0

tf.logging.set_verbosity(tf.logging.INFO)
with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as tfs:
    
    init = tf.global_variables_initializer()
    tfs.run(init)
    writer = tf.summary.FileWriter('tflogs', tfs.graph)
    print('---')
    print(tfs.run(y2, {x2: [1, 2, 3, 4]}))

---
[0. 1. 2. 3.]


In [ ]:
!tensorboard --logdir="tflogs"

W1126 17:02:58.671924 Reloader tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
W1126 17:02:58.671923 140566763906816 tf_logging.py:120] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
TensorBoard 1.12.0 at http://945ad8be7456:6006 (Press CTRL+C to quit)


In [ ]:
from IPython.display import clear_output, Image, display, HTML

def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe)
            
show_graph(tf.get_default_graph().as_graph_def())
            
gdef = tf.GraphDef()
from google.protobuf import text_format
text_format.Merge(open("tf_persistent.pbtxt").read(), gdef)
show_graph(gdef)