References: https://www.tensorflow.org/guide/datasets

In [1]:
import numpy as np
import tensorflow as tf
x = np.arange(0, 100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
# create dataset object from numpy array
dx = tf.data.Dataset.from_tensor_slices(x)
print(dx)

<TensorSliceDataset shapes: (), types: tf.int64>


In [3]:
# create a one-shot iterator
iterator = dx.make_one_shot_iterator()
# extract an element
next_element = iterator.get_next()

In [4]:
with tf.Session() as sess:
    for i in range(11):
        val = sess.run(next_element)
        print(val)

0
1
2
3
4
5
6
7
8
9
10


In [33]:
y = np.arange(5, 10)
print(y)
dy = tf.data.Dataset.from_tensor_slices(y)
iterator2 = dy.make_initializable_iterator()
next_element2 = iterator2.get_next()
with tf.Session() as sess:
    #ssess.run(iterator2.initializer)
    for i in range(0, 15):
        if (i % 5 == 0):
            print('Calling init')
            sess.run(iterator2.initializer)
          
        val = sess.run(next_element2)
        print(val) 
        

[5 6 7 8 9]
Calling init
5
6
7
8
9
Calling init
5
6
7
8
9
Calling init
5
6
7
8
9


In [42]:
x3 = np.arange(5, 11)
dx3 = tf.data.Dataset.from_tensor_slices(x3).batch(3)
iterator3 = dx3.make_initializable_iterator()
next_element3 = iterator3.get_next()

with tf.Session() as sess:
    sess.run(iterator3.initializer)
    for i in range(1, 15):
        val = sess.run(next_element3)
        print(val)
        
        if ((i * 3) % 6) == 0:
            print('Calling')
            sess.run(iterator3.initializer)

[5 6 7]
[ 8  9 10]
Calling
[5 6 7]
[ 8  9 10]
Calling
[5 6 7]
[ 8  9 10]
Calling
[5 6 7]
[ 8  9 10]
Calling
[5 6 7]
[ 8  9 10]
Calling
[5 6 7]
[ 8  9 10]
Calling
[5 6 7]
[ 8  9 10]
Calling


In [53]:
x4 = np.arange(0, 10)
y4 = np.arange(100, 110)
print(str(len(x4)) + str(len(y4)))
# create dataset objects from the arrays
dx4 = tf.data.Dataset.from_tensor_slices(x4)
dy4 = tf.data.Dataset.from_tensor_slices(y4)
# zip the two datasets together
dcomb = tf.data.Dataset.zip((dx4, dy4)).repeat().batch(2)
iterator4 = dcomb.make_initializable_iterator()
# extract an element
next_element4 = iterator4.get_next()
with tf.Session() as sess:
    sess.run(iterator4.initializer)
    for i in range(1, 20):
        '''
        if (((i * 2) % 20) == 0) or (i == 1):
            print('Calling')
            sess.run(iterator4.initializer)
        '''
        val = sess.run(next_element4)
        print(val)
        

1010
(array([0, 1]), array([100, 101]))
(array([2, 3]), array([102, 103]))
(array([4, 5]), array([104, 105]))
(array([6, 7]), array([106, 107]))
(array([8, 9]), array([108, 109]))
(array([0, 1]), array([100, 101]))
(array([2, 3]), array([102, 103]))
(array([4, 5]), array([104, 105]))
(array([6, 7]), array([106, 107]))
(array([8, 9]), array([108, 109]))
(array([0, 1]), array([100, 101]))
(array([2, 3]), array([102, 103]))
(array([4, 5]), array([104, 105]))
(array([6, 7]), array([106, 107]))
(array([8, 9]), array([108, 109]))
(array([0, 1]), array([100, 101]))
(array([2, 3]), array([102, 103]))
(array([4, 5]), array([104, 105]))
(array([6, 7]), array([106, 107]))
